### ISSUE TITLE
v2_new_controls

### ISSUE THREAD

**Issue by ejaronne** [mitre/aws-foundations-cis-baseline#112]
For the v2_update branch, 23 brand new controls are introduced that need fresh logic / inspec describe blocks:

1.6
1.7
1.13
1.19
1.20
1.21
1.22
2.1.1
2.1.2
2.1.3
2.1.4
2.2.1
2.3.1
2.3.2
2.3.3
2.4.1
3.10
3.11
4.15
4.16
5.1
5.3
5.6

**Comment by aaronlippold** [comment]
Fixed by #[2a56937](https://github.com/mitre/aws-foundations-cis-baseline/commit/2a569371ef76ec458632b747f771219714fd5d58)
