### ISSUE TITLE
Update the controls to support desc tags (ex. for check/fix text)

### ISSUE THREAD

**Issue by aaronlippold** [mitre/aws-foundations-cis-baseline#14]
InSpec 3.x added the ability to have proper subsections in the controls rather than overloading the functions of 'tag'.

Update the controls to use sub-sections by default and not `tag`

**Comment by Amndeep7** [comment]
@aaronlippold is this still applicable?

**Comment by Amndeep7** [comment]
Briefly looking through it, I actually think desc tags are being used so I'm closing this issue.  Please reopen if necessary @aaronlippold.
