### ISSUE TITLE
Uploading profile to Chef Automate returns AwsSingularResourceMixin errors

### ISSUE THREAD

**Issue by pnwdylan** [mitre/aws-foundations-cis-baseline#19]
Hello,

Every time i am uploading the inspec profile to AWS Chef Automate/Compliance server, I receive the following error messages : 
1\nlibraries/aws_iam_policy.rb:15:in `\u003cclass:AwsIamPolicy\u003e': uninitialized constant #\u003cClass:0x0000000003652428\u003e::AwsIamPolicy::AwsSingularResourceMixin (NameError)\n\tfrom libraries/aws_iam_policy.rb:5:in
----
Error during profile upload:
{"summary":{"valid":false,"timestamp":"","location":"","controls":0},"errors":[{"msg":"InSpec check failed for /var/opt/delivery/compliance/profiles/.tmp/inspec-upload359376957.tar.gz with message: exit status 1\nlibraries/aws_iam_policy.rb:15:in `\u003cclass:AwsIamPolicy\u003e': uninitialized constant #\u003cClass:0x0000000003652428\u003e::AwsIamPolicy::AwsSingularResourceMixin (NameError)\n\tfrom libraries/aws_iam_policy.rb:5:in `load_with_context'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:157:in `instance_eval'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:157:in `load_with_context'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:146:in `load_library_file'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:133:in `block in load_libraries'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:131:in `each'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile_context.rb:131:in `load_libraries'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:194:in `load_libraries'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:469:in `load_checks_params'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:463:in `load_params'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:157:in `params'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:323:in `controls_count'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/profile.rb:294:in `check'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/lib/inspec/cli.rb:76:in `check'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'\n\tfrom /opt/delivery/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.51.18/bin/inspec:12:in `\u003ctop (required)\u003e'\n\tfrom /opt/delivery/bin/inspec:56:in `load'\n\tfrom /opt/delivery/bin/inspec:56:in `\u003cmain\u003e'\n"}],"warnings":null}
----

Any suggestions on how i can upload this profile to the Compliance server?

**Comment by aaronlippold** [comment]
Hi sorry for the late reply, I will have @rx294 take a look into this.

**Comment by rx294** [comment]
Hey @Dylan-in-seattle please let us know if the issue still exists with the recent updates.

Thank you.

**Comment by Amndeep7** [comment]
Due to lack of response, I'm closing this issue.  @pnwdylan, please make a new issue if you're still having problems.
