### ISSUE TITLE
Fix needed for control 1.3

### ISSUE THREAD

**Issue by rx294** [mitre/aws-foundations-cis-baseline#29]
password_last_used_days_ago >= 90 check should be filtered for users with console access

https://github.com/mitre/cis-aws-foundations-baseline/blob/master/controls/cis-aws-foundations-1.3.rb#L64-L66

**Comment by karikarshivani** [comment]
@rx294 I think it's safe to close the issue because the check is being performed now:
https://github.com/mitre/aws-foundations-cis-baseline/blob/master/controls/aws-foundations-cis-1.3.rb#L55

Thoughts?

**Comment by rx294** [comment]
@karikarshivani agreed. The fix is satisfactory. Closing this issue.
